/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DashboardWorkspaceRouteImport } from './routes/dashboard/workspace'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard/api-keys'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSchemaPushRouteImport } from './routes/api/schema/push'
import { Route as ApiSchemaPullRouteImport } from './routes/api/schema/pull'
import { Route as ApiSchemaProjectsRouteImport } from './routes/api/schema/projects'
import { Route as ApiSchemaItemsRouteImport } from './routes/api/schema/items'
import { Route as ApiSchemaCollectionsRouteImport } from './routes/api/schema/collections'
import { Route as ApiSchemaCollectionItemsRouteImport } from './routes/api/schema/collection-items'
import { Route as ApiCollectionsItemsRouteImport } from './routes/api/collections/items'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardCollectionsNameRouteRouteImport } from './routes/dashboard/collections/$name/route'
import { Route as DashboardCollectionsNameIndexRouteImport } from './routes/dashboard/collections/$name/index'
import { Route as DashboardCollectionsNameSchemaRouteImport } from './routes/dashboard/collections/$name/schema'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceRoute = DashboardWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaPushRoute = ApiSchemaPushRouteImport.update({
  id: '/api/schema/push',
  path: '/api/schema/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaPullRoute = ApiSchemaPullRouteImport.update({
  id: '/api/schema/pull',
  path: '/api/schema/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaProjectsRoute = ApiSchemaProjectsRouteImport.update({
  id: '/api/schema/projects',
  path: '/api/schema/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaItemsRoute = ApiSchemaItemsRouteImport.update({
  id: '/api/schema/items',
  path: '/api/schema/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaCollectionsRoute = ApiSchemaCollectionsRouteImport.update({
  id: '/api/schema/collections',
  path: '/api/schema/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaCollectionItemsRoute =
  ApiSchemaCollectionItemsRouteImport.update({
    id: '/api/schema/collection-items',
    path: '/api/schema/collection-items',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCollectionsItemsRoute = ApiCollectionsItemsRouteImport.update({
  id: '/api/collections/items',
  path: '/api/collections/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCollectionsNameRouteRoute =
  DashboardCollectionsNameRouteRouteImport.update({
    id: '/collections/$name',
    path: '/collections/$name',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCollectionsNameIndexRoute =
  DashboardCollectionsNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCollectionsNameRouteRoute,
  } as any)
const DashboardCollectionsNameSchemaRoute =
  DashboardCollectionsNameSchemaRouteImport.update({
    id: '/schema',
    path: '/schema',
    getParentRoute: () => DashboardCollectionsNameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/docs/$': typeof DocsSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/collections/$name': typeof DashboardCollectionsNameRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/collections/items': typeof ApiCollectionsItemsRoute
  '/api/schema/collection-items': typeof ApiSchemaCollectionItemsRoute
  '/api/schema/collections': typeof ApiSchemaCollectionsRoute
  '/api/schema/items': typeof ApiSchemaItemsRoute
  '/api/schema/projects': typeof ApiSchemaProjectsRoute
  '/api/schema/pull': typeof ApiSchemaPullRoute
  '/api/schema/push': typeof ApiSchemaPushRoute
  '/dashboard/collections/$name/schema': typeof DashboardCollectionsNameSchemaRoute
  '/dashboard/collections/$name/': typeof DashboardCollectionsNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/docs/$': typeof DocsSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/collections/items': typeof ApiCollectionsItemsRoute
  '/api/schema/collection-items': typeof ApiSchemaCollectionItemsRoute
  '/api/schema/collections': typeof ApiSchemaCollectionsRoute
  '/api/schema/items': typeof ApiSchemaItemsRoute
  '/api/schema/projects': typeof ApiSchemaProjectsRoute
  '/api/schema/pull': typeof ApiSchemaPullRoute
  '/api/schema/push': typeof ApiSchemaPushRoute
  '/dashboard/collections/$name/schema': typeof DashboardCollectionsNameSchemaRoute
  '/dashboard/collections/$name': typeof DashboardCollectionsNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/search': typeof ApiSearchRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/docs/$': typeof DocsSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/collections/$name': typeof DashboardCollectionsNameRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/collections/items': typeof ApiCollectionsItemsRoute
  '/api/schema/collection-items': typeof ApiSchemaCollectionItemsRoute
  '/api/schema/collections': typeof ApiSchemaCollectionsRoute
  '/api/schema/items': typeof ApiSchemaItemsRoute
  '/api/schema/projects': typeof ApiSchemaProjectsRoute
  '/api/schema/pull': typeof ApiSchemaPullRoute
  '/api/schema/push': typeof ApiSchemaPushRoute
  '/dashboard/collections/$name/schema': typeof DashboardCollectionsNameSchemaRoute
  '/dashboard/collections/$name/': typeof DashboardCollectionsNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/search'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/team'
    | '/dashboard/workspace'
    | '/docs/$'
    | '/invite/$token'
    | '/dashboard/'
    | '/dashboard/collections/$name'
    | '/api/auth/$'
    | '/api/collections/items'
    | '/api/schema/collection-items'
    | '/api/schema/collections'
    | '/api/schema/items'
    | '/api/schema/projects'
    | '/api/schema/pull'
    | '/api/schema/push'
    | '/dashboard/collections/$name/schema'
    | '/dashboard/collections/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/search'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/team'
    | '/dashboard/workspace'
    | '/docs/$'
    | '/invite/$token'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/collections/items'
    | '/api/schema/collection-items'
    | '/api/schema/collections'
    | '/api/schema/items'
    | '/api/schema/projects'
    | '/api/schema/pull'
    | '/api/schema/push'
    | '/dashboard/collections/$name/schema'
    | '/dashboard/collections/$name'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/search'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/team'
    | '/dashboard/workspace'
    | '/docs/$'
    | '/invite/$token'
    | '/dashboard/'
    | '/dashboard/collections/$name'
    | '/api/auth/$'
    | '/api/collections/items'
    | '/api/schema/collection-items'
    | '/api/schema/collections'
    | '/api/schema/items'
    | '/api/schema/projects'
    | '/api/schema/pull'
    | '/api/schema/push'
    | '/dashboard/collections/$name/schema'
    | '/dashboard/collections/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCollectionsItemsRoute: typeof ApiCollectionsItemsRoute
  ApiSchemaCollectionItemsRoute: typeof ApiSchemaCollectionItemsRoute
  ApiSchemaCollectionsRoute: typeof ApiSchemaCollectionsRoute
  ApiSchemaItemsRoute: typeof ApiSchemaItemsRoute
  ApiSchemaProjectsRoute: typeof ApiSchemaProjectsRoute
  ApiSchemaPullRoute: typeof ApiSchemaPullRoute
  ApiSchemaPushRoute: typeof ApiSchemaPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspace': {
      id: '/dashboard/workspace'
      path: '/workspace'
      fullPath: '/dashboard/workspace'
      preLoaderRoute: typeof DashboardWorkspaceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema/push': {
      id: '/api/schema/push'
      path: '/api/schema/push'
      fullPath: '/api/schema/push'
      preLoaderRoute: typeof ApiSchemaPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema/pull': {
      id: '/api/schema/pull'
      path: '/api/schema/pull'
      fullPath: '/api/schema/pull'
      preLoaderRoute: typeof ApiSchemaPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema/projects': {
      id: '/api/schema/projects'
      path: '/api/schema/projects'
      fullPath: '/api/schema/projects'
      preLoaderRoute: typeof ApiSchemaProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema/items': {
      id: '/api/schema/items'
      path: '/api/schema/items'
      fullPath: '/api/schema/items'
      preLoaderRoute: typeof ApiSchemaItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema/collections': {
      id: '/api/schema/collections'
      path: '/api/schema/collections'
      fullPath: '/api/schema/collections'
      preLoaderRoute: typeof ApiSchemaCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema/collection-items': {
      id: '/api/schema/collection-items'
      path: '/api/schema/collection-items'
      fullPath: '/api/schema/collection-items'
      preLoaderRoute: typeof ApiSchemaCollectionItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections/items': {
      id: '/api/collections/items'
      path: '/api/collections/items'
      fullPath: '/api/collections/items'
      preLoaderRoute: typeof ApiCollectionsItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/collections/$name': {
      id: '/dashboard/collections/$name'
      path: '/collections/$name'
      fullPath: '/dashboard/collections/$name'
      preLoaderRoute: typeof DashboardCollectionsNameRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/collections/$name/': {
      id: '/dashboard/collections/$name/'
      path: '/'
      fullPath: '/dashboard/collections/$name/'
      preLoaderRoute: typeof DashboardCollectionsNameIndexRouteImport
      parentRoute: typeof DashboardCollectionsNameRouteRoute
    }
    '/dashboard/collections/$name/schema': {
      id: '/dashboard/collections/$name/schema'
      path: '/schema'
      fullPath: '/dashboard/collections/$name/schema'
      preLoaderRoute: typeof DashboardCollectionsNameSchemaRouteImport
      parentRoute: typeof DashboardCollectionsNameRouteRoute
    }
  }
}

interface DashboardCollectionsNameRouteRouteChildren {
  DashboardCollectionsNameSchemaRoute: typeof DashboardCollectionsNameSchemaRoute
  DashboardCollectionsNameIndexRoute: typeof DashboardCollectionsNameIndexRoute
}

const DashboardCollectionsNameRouteRouteChildren: DashboardCollectionsNameRouteRouteChildren =
  {
    DashboardCollectionsNameSchemaRoute: DashboardCollectionsNameSchemaRoute,
    DashboardCollectionsNameIndexRoute: DashboardCollectionsNameIndexRoute,
  }

const DashboardCollectionsNameRouteRouteWithChildren =
  DashboardCollectionsNameRouteRoute._addFileChildren(
    DashboardCollectionsNameRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardWorkspaceRoute: typeof DashboardWorkspaceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCollectionsNameRouteRoute: typeof DashboardCollectionsNameRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardWorkspaceRoute: DashboardWorkspaceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCollectionsNameRouteRoute:
    DashboardCollectionsNameRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCollectionsItemsRoute: ApiCollectionsItemsRoute,
  ApiSchemaCollectionItemsRoute: ApiSchemaCollectionItemsRoute,
  ApiSchemaCollectionsRoute: ApiSchemaCollectionsRoute,
  ApiSchemaItemsRoute: ApiSchemaItemsRoute,
  ApiSchemaProjectsRoute: ApiSchemaProjectsRoute,
  ApiSchemaPullRoute: ApiSchemaPullRoute,
  ApiSchemaPushRoute: ApiSchemaPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
